[workspace]
members = ["cvlr_by_example/first_example"]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.dependencies]
cvlr = { git = "https://github.com/Certora/cvlr", branch = "main" }
