[workspace]
members = ["first_example"]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.dependencies]
cvlr = { git = "https://github.com/Certora/solana-cvt.git", branch = "arie/cvlr" }