# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details

version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0.0

parameters:
  run_workflow_nightly:
    default: false
    type: boolean
  
  certora_cli_package:
    default: "certora-cli-alpha-master"
    type: string

  path_to_confs:
    default: "."
    type: string
  
  prover_version:
    default: "jorge/solana-dev"
    type: string
      

commands:

  install_conf_runner_infra:
    steps:

      - run:
          name: Install ConfRunnerInfra
          command: pip3.11 install git+ssh://git@github.com/Certora/ConfRunnerInfra.git


  install_certora_cli:
    steps:
      - run:
          name: Get the current master of EVMVerifier with << pipeline.parameters.certora_cli_package >>
          command: pip3.11 install << pipeline.parameters.certora_cli_package >>

  configure_aws:
    steps:
      - aws-cli/setup:
          role_arn: $CIRCLECI_OIDC_CDK_STAGING
          region: $AWS_REGION
          session_duration: '8100'

  compile_blog_example:
    steps:
      - run:
          name: Compile SOL To bytecode
          command: |
            source ~/.profile
            cd BlogExample/IntegrityOfMint
            cargo build-sbf --arch=sbfv1 --features no-entrypoint certora
  
  regression:
    steps:
    - run:
        name: Run Regression Tests
        command: |
          Regression --path << pipeline.parameters.path_to_confs >> \
                    --prover_version << pipeline.parameters.prover_version >> \
                    --json_flags "{\"use_per_rule_cache\": false, \"unused_summary_hard_fail\": \"on\", \"assert_autofinder_success\": true, \"optimistic_loop\": true, \"group_id\": \"$CIRCLE_WORKFLOW_ID\"}" \
                    --send_message




jobs:
  solana_nightly:
    parameters:
      certora_ci_name:
        type: string
    docker:
      - image: &img public.ecr.aws/certora/cvt-image:2024.03.11-3376-a52d026
    resource_class: small
    environment:
      CERTORA_DISABLE_AUTO_CACHE: "1"
      CERTORA_CI_CLIENT: << parameters.certora_ci_name >>
    working_directory: ~/repo
    steps:
      
      - checkout

      - install_certora_cli

      - configure_aws 

      - install_conf_runner_infra

      - compile_blog_example

      - regression

      - store_artifacts:
          path: Report.csv
          destination: reports
      
      - store_test_results:
          path: ~/repo



workflows:
  version: 2
  # Nightly builds will run every day at 4am GMT
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - solana_nightly:
          certora_ci_name: "SOL Examples Nightly"
          context: aws_staging

  # run from CircleCI with the boolean parameter run_workflow_nightly set to true
  manual:
    when: << pipeline.parameters.run_workflow_nightly >>
    jobs:
      - solana_nightly:
          certora_ci_name: "SOL Examples Manual"
          context: aws_staging